schema_version: 1

context:
  name: tree-sitter-sql
  version: 0.3.8

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/DerekStride/tree-sitter-sql/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 1e0e9fcf087b964292bda7ca566f41a63b8e336b89956546299ba2bf825dd7e2

build:
  number: 0
  script:
    - tree-sitter generate
    - ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - nodejs
    - tree-sitter-cli
  host:
    - pip
    - python
    - setuptools >=43
  run:
    - python

tests:
  - python:
      imports:
        - tree_sitter_sql
  - requirements:
      run:
        - pip
    script:
      - pip check

about:
  summary: SQL grammar for tree-sitter
  license: MIT
  license_file:
    - LICENSE
  homepage: https://github.com/DerekStride/tree-sitter-sql

extra:
  recipe-maintainers:
    - xhochy
